language: java

addons:
  sonarcloud:
    organization: "msdehghan-github"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

dist: xenial

env:
  global:
    - SPRING_PROFILES_ACTIVE=ci

services:
  - mysql