language: java

addons:
  sonarcloud:
    organization: "msdehghan-github"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

dist: xenial

env:
  global:
    - SPRING_PROFILES_ACTIVE=ci

services:
  - mysql

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AMAZON_ACCESS_KEY"
  secret_access_key:
    secure: "$AMAZON_SECRET_ACCESS_KEY"
  region: "us-east-1"
  app: "ecommerce"
  env: "ecommerce-env"
  bucket_name: "elasticbeanstalk-us-east-1-340919845758"
  zip_file: "$TRAVIS_BUILD_DIR/target/application.jar"
  skip_cleanup: true